### ISSUE TITLE
Reflection warnings in java-time.single-field

### ISSUE THREAD

**Issue by glchapman** [dm3/clojure.java-time#1]
Just trying out java-time with clojure 1.8-RC5, I get the following:

user=> (require '[java-time :as t :reload-all true])
Reflection warning, java_time/single_field.clj:175:1 - call to static method of on java.time.MonthDay can't be resolved (argument types: java.time.Month, unknown).
Reflection warning, java_time/single_field.clj:183:1 - call to static method of on java.time.YearMonth can't be resolved (argument types: unknown, long).
Reflection warning, java_time/single_field.clj:183:1 - call to static method of on java.time.YearMonth can't be resolved (argument types: unknown, long).
Reflection warning, java_time/single_field.clj:183:1 - call to static method of on java.time.YearMonth can't be resolved (argument types: unknown, java.time.Month).

It seems the "unknown" types should be hinted to ints to please the clojure compiler. I note the relevant ctors have int in a comp; apparently, this is not sufficient for the clojure compiler to figure out that the ctors are returning ints.

**Comment by dm3** [comment]
Thanks, I'll take a look at this.

**Comment by dm3** [comment]
Fixed in 0.2.1
