### ISSUE TITLE
three-next-days-example not working in README

### ISSUE THREAD

**Issue by TimoKramer** [dm3/clojure.java-time#12]
Hi there,

I am a beginner and wanted to use your example to get the next three days from today. That didn't work out as far as I can judge.

The repl tells me:
`ArityException Wrong number of args (3) passed to: core/iterate  clojure.lang.AFn.throwArity (AFn.java:429)`

iterate indeed takes only two arguments and there are three. I would have created a pull-request but I am not able to solve this simple problem, sorry.

```
Three next days?

(take 3 (iterate plus now (days 1)))
=> (#object[java.time.LocalDate "2015-09-28"]
    #object[java.time.LocalDate "2015-09-29"]
    #object[java.time.LocalDate "2015-09-30"])

**Comment by dm3** [comment]
Hey,

it seems you are using `clojure.core/iterate` instead of `java-time/iterate`. Could you try:

```clojure
(require '[java-time :as j])
(take 3 (j/iterate j/plus (j/local-date) (j/days 1)))
```

?

**Comment by TimoKramer** [comment]
right, now it is obvious. thanks, and keep up the good work!
