### ISSUE TITLE
Predicate for when something is a date time type

### ISSUE THREAD

**Issue by lvh** [dm3/clojure.java-time#13]
I have a nested data structure and I want to convert all the date time objects in it to ISO8601 timestamps during serialization. So, I need to find out what the timestamps are. I can't just try converting with `instant`, because it'll try to convert strings, which I don't want.

`inst?` is almost what I want, but Joda Time instances don't satisfy `Inst`. This could be solved with something along the lines of the following:

```clojure
(try
  (Class/forName "org.joda.time.Instant")
  (eval
   '(extend-protocol Inst
      org.joda.time.Instant
      (inst-ms* [inst] (inst-ms* (jt/instant inst)))

      org.joda.time.DateTime
      (inst-ms* [inst] (inst-ms* (jt/instant inst)))))
  (catch ClassNotFoundException cnfe))
```

(though this project already has a better `when-joda` macro :))

Do you have a preferred solution?

**Comment by dm3** [comment]
do I understand correctly that you have data with `org.joda.time.Instant`/`org.joda.time.DateTime` fields inside which you want to serialize into ISO8601 strings?

Haven't actually noticed `Inst` before. Your solution would definitely work. It has an additional benefit of not transforming the datastructure just to change the type of instants. Also, there shouldn't be any problems with globally extending `Inst` for `DateTime` as in Joda-Time it is analogous to an Instant.

I don't think there's anything in this project that can help you do what you want to do in a more direct way.

**Comment by lvh** [comment]
Yeah, my problem is fully solved by this piece of code, but perhaps it'd be good to add this to the portability code here so it automatically works for everyone :)

It might make more sense in clj-time instead?

**Comment by dm3** [comment]
Hmm, I think adding 

```
(extend-type org.joda.time.ReadableInstant
     Inst (inst-ms* [inst] (.getMillis inst)))
```

shouldn't break anything. However, a library shouldn't be extending foreign types with foreign protocols. This may have a place in an explicitly invoked method or documentation though.

**Comment by dm3** [comment]
Added a `when-joda-time-loaded` macro to the public API. Updated docs.

**Comment by lvh** [comment]
Cool, thanks :) I look forward to using this feature in a new release.
