### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by alex314159** [dm3/clojure.java-time#14]
Clojure beginner here. Tried installing as a lein dependency but I seem to be missing quite a few functions, for example:

zdttest.core=> (day-of-week now)
#object[java.time.DayOfWeek 0x3aad4eed "SUNDAY"]

zdttest.core=> (day-of-year now)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: day-of-year in this context, compiling:(/tmp/form-init3614178941667070356.clj:1:1) 

zdttest.core=> (day-of-month now)
CompilerException java.lang.RuntimeException: Unable to resolve symbol: day-of-month in this context, compiling:(/tmp/form-init3614178941667070356.clj:1:1) 

This is my project.clj file:

(defproject zdttest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.8.0"] [clojure.java-time "0.3.0"]]
  :main ^:skip-aot zdttest.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})

How can I fix this? Thank you,

**Comment by dm3** [comment]
Hi,

it seems you haven't `use`d the `java-time` namespace in your project as described in the [Usage](https://github.com/dm3/clojure.java-time#usage) section:

```clojure
(use 'java-time)
```

This should fix your problems :)

**Comment by alex314159** [comment]
Thanks for the quick feedback Vadim but getting the same issue... running lein repl on the following file

    (ns zdttest.core
      (:gen-class)
    )
    (use 'java-time)

**Comment by dm3** [comment]
Ok, let's start simpler. Try the following:

1. Open a new repl in the directory where you have your `project.clj` with `clojure.java-time` as the dependency: `lein repl`
2. In the repl, type: `(use 'java-time)`
3. Create a local date-time: `(def date (local-date))`

**Comment by alex314159** [comment]
This works (and worked before using require too). Most functions are there, and it's a pleasure to use, but some functions are (seemingly randomly) missing.

If that's any help - (count (keys (ns-publics 'java-time))) returns 123 with the following functions:

(period year-month? wednesday? contains? units minutes month? system-clock end with-clock local-date-time? with-offset-same-instant iterate negate month-day? with-zone millis weeks standard-days range sql-time weekday? properties to-java-date to-millis-from-epoch after? unit? move-end-to min supports? format local-date-time negative? weekend? overlaps? with-max-value zone-offset overlap zoned-date-time? duration? zoned-date-time truncate-to nanos local-time offset-time instant day-of-week? offset-date-time move-start-to unit leap? offset-date-time? property java-date value-range move-end-by formatter local-date? value day-of-week as fields with-smallest-max-value available-zone-ids to-sql-timestamp friday? offset-clock zero? months month start convert-amount duration minus days saturday? field min-value adjust seconds micros before? with-clock-fn monday? sql-timestamp max-value largest-min-value field? year year? with-zone-same-instant smallest-max-value period? instant? move-start-by abs local-time? month-day multiply-by tuesday? offset-time? max chronology local-date plus with-min-value year-month tick-clock with-value time-between zone-id gap sunday? abuts? fixed-clock hours as-map years sql-date thursday? with-offset to-sql-date with-largest-min-value)

**Comment by dm3** [comment]
I see. Sorry about being obtuse.

The functions you're lacking will appear if you include the following optional dependency: `[org.threeten/threeten-extra "1.0"]`. This dependency contains an implementation for `DayOfYear`, `DayOfMonth`, `Interval` and a few other types.

**Comment by alex314159** [comment]
Great! Sorry I didn't pay attention to this in the README file, thanks so much for your quick help!
