### ISSUE TITLE
Is this library compatible with recent versions of threeten-extra?

### ISSUE THREAD

**Issue by WilliamParker** [dm3/clojure.java-time#16]
From the README:

````
If you add an optional [org.threeten/threeten-extra "0.9"] dependency to the project, you will get an Interval, AmPm, DayOfMonth, DayOfYear, Quarter and YearQuarter data types as well as a couple more adjusters.
````

Per the [threeten-extra project readme](https://github.com/ThreeTen/threeten-extra) the most recent version of threeten-extra is 1.2.  Are there any known incompatibilities between more recent versions of threeten-extra and clojure.java-time?

**Comment by dm3** [comment]
As long as the new versions are only adding APIs - it should be fine. I haven't tried though. The [Changelog](http://www.threeten.org/threeten-extra/changes-report.html) indicates a few new types were added and the parsing for existing types improved, so I'd expect Clojure.Java-Time to work with 1.2 without problems.

Feel free to update the version in the `project.clj` and run the test suite with `lein test`/`lein test-all`. I'd gladly accept reasonable contributions to the library!

**Comment by dm3** [comment]
Just ran tests with 1.2. We should be ok!

**Comment by WilliamParker** [comment]
Excellent, thanks for looking at this @dm3
