### ISSUE TITLE
Is there a reason that java-time.format/parse is not exposed in the main namespace?

### ISSUE THREAD

**Issue by seancorfield** [dm3/clojure.java-time#18]
Is it just an oversight on the imports?

Are there any other unexpectedly hidden functions?

(this came up when I pointed a beginner at `clojure.java-time` and they were trying to parse string)

**Comment by dm3** [comment]
The way parsing is done is through the "typed" functions, e.g. `(local-date "MM/yyyy/dd" "09/2015/28")`. This way the function can return a concrete result type. `java-time.format/parse` returns a `TemporalAccessor` and needs to be paired with a function that would construct a concrete type out of it to make it work. 

I would consider adding it to the public API if you have any good use cases.

**Comment by seancorfield** [comment]
I totally missed that you could pass a format string as the first argument to get custom parsing -- I'd only seen that it would attempt to parse a single string argument. Thank you!
