### ISSUE TITLE
Using `as` with `month-day` throws exception

### ISSUE THREAD

**Issue by mrwizard82d1** [dm3/clojure.java-time#20]
I am writing a simple application for tracking my own time. I wanted to use an expression like `(as the-month-day :month-of-year :day-of-month)`. However, this expression failed reporting that `MonthDay` did not implement the `As` protocol.

In a few moments, I will create a pull request with the changes that I made to both tests and source code to resolve this issue.

**Comment by dm3** [comment]
Closed by #21. Will try to release a new version shortly :)

**Comment by mrwizard82d1** [comment]
Thanks, Vadim!
