### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by coltnz** [dm3/clojure.java-time#22]
Unfortunately it's in breach of the Clojure and Java trademarks to use them in your own software name.  There is a valid risk of confusion too.

You might as well change it before Oracle makes you :)  

e.g. from Clojure's license 

   6. Trademarks. This License does not grant permission to use the trade
      names, trademarks, service marks, or product names of the Licensor,
      except as required for reasonable and customary use in describing the
      origin of the Work and reproducing the content of the NOTICE file.

**Comment by dm3** [comment]
You might be right, although there seems to be a lot of offenders in the opensource. E.g. https://github.com/square/javapoet or all the projects in [Clojars](https://clojars.org/search?q=clojure) with "Clojure" as part of their name. Adding "clojure" to the name seems to be the best way to indicate  a Clojure-specific implementation of a protocol/wrapper.

I don't mind changing the name. However, it's a very insignificant project in the grand scheme of things. It doesn't make any money or denigrate the Java or Clojure trademarks. Furthermore, I even got a PR from @stuarthalloway so maybe Clojure people are OK with the name? :)

**Comment by coltnz** [comment]
I have seen Rich comment as such on a library in the past.. <shrug>.  I'm a little wary myself since we've been through library audits and this might have attracted attention even if I as a user wouldn't be in breach (I think, IANAL).

**Comment by dm3** [comment]
We can put this question up on the Clojure mailing list. See if there's any concern from the wider community or from Cognitect. Feel free to start the discussion!

**Comment by frenchy64** [comment]
Clarified naming in readme.
