### ISSUE TITLE
How to go from "10:00" strings to inverval?

### ISSUE THREAD

**Issue by WorldsEndless** [dm3/clojure.java-time#23]
I realize this is not the ideal place for questions, but searching for the past hour is not getting me an answer. Suppose I am provided with three strings `["10:00" "12:00" "17:00"]`.  I need to be able to produce the right data structures to determine if one is within the interval of the other two; however, for the life of me I can't figure out how to do this. Doing `local-time` on any of them works, but intervals require instants and instants can't be created that way. Help would be much appreciated.

**Comment by WorldsEndless** [comment]
Ah; I didn't realize that "local-time" in Java parlance meant "no timezone" as opposed to "local timezone'. I solved this as follows:

```
(defn instant-from-hour
  "example of constructing a 10:00i nstant"
  [hour-string]
  (-> hour-string
      time/local-time
      (.atDate (time/local-date))
      (.atZone (java.time.ZoneId/of "Etc/GMT-7"))
      (time/instant)))
```

**Comment by dm3** [comment]
@WorldsEndless in case you want a more succinct solution:

```clojure
(time/instant (time/local-time "10:00") "Etc/GMT-7")
```
All of the constructors like `time/local-date`, `time/local-time`, etc. accept multiple arguments. It's not trivial to discover what exactly is and isn't accepted and all of the combinations would be hard to describe in documentation. Admittedly, I should have put some effort into some sort of visualisation, e.g. given a "time without date" input and a time zone, how do I get to a current time instant, but I didn't. 

Anyway, you can see the transformation path that takes a `local-time` and a time-zone string to a `time/instant` like so:

```clojure
user=> (require '[java-time.repl :as r])
user=> (r/show-path [java.time.LocalTime String] java.time.Instant)
{:cost 5.5
 :path [[#object[java_time.graph.Types 0x6722af3c "[java.time.LocalTime java.lang.String]"]
         #object[java_time.graph.Types 0x18c23e96 "[java.time.LocalDateTime java.lang.String]"]]
        [#object[java_time.graph.Types 0x63c80d7b "[java.time.LocalDateTime java.lang.String]"]
         #object[java_time.graph.Types 0x4a23c3f2 "[java.time.LocalDateTime java.time.ZoneId]"]]
        [#object[java_time.graph.Types 0x388acec5 "[java.time.LocalDateTime java.time.ZoneId]"]
         #object[java_time.graph.Types 0x31b571cc "[java.time.ZonedDateTime]"]]
        [#object[java_time.graph.Types 0x465d7ca3 "[java.time.ZonedDateTime]"]
         #object[java_time.graph.Types 0x28cf6e4b "[java.time.Instant]"]]]}
```
Hope this helps!
