### ISSUE TITLE
formatter keys

### ISSUE THREAD

**Issue by waffletower** [dm3/clojure.java-time#24]
for performance and coding consistency I recommend representing predefined formatters in the java-time.format namespace using keywords rather than strings.  I could put in a PR for this if there is agreement.

**Comment by dm3** [comment]
Hi, sorry for not responding earlier!

There's already a set of predefined formatters supported by `j/format`. These are the formatters defined in [java.time.format.DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html):

```
user=> (keys java-time.format/predefined-formatters)
("iso-offset-time"
 "iso-local-time"
 "iso-local-date-time"
 "iso-offset-date"
 "iso-time"
 "iso-week-date"
 "basic-iso-date"
 "rfc-1123-date-time"
 "iso-ordinal-date"
 "iso-zoned-date-time"
 "iso-instant"
 "iso-date-time"
 "iso-offset-date-time"
 "iso-date"
 "iso-local-date")
```

so you can do the following:

```
user=> (j/format :iso-offset-time (j/zoned-date-time))
"21:10:00.000+01:00"
user=> (j/format :iso-time (j/zoned-date-time))
"21:11:00.000+01:00"
user=> (j/format :iso-date-time (j/zoned-date-time))
"2018-07-12T21:12:00.000+01:00[Europe/London]"
user=> (j/format :iso-local-date (j/zoned-date-time))
"2018-07-12"
```

We can always improve the documentation if you think this can be made clearer. Happy to review any PR/discuss changes.

**Comment by waffletower** [comment]
This is really a minor issue.  It is nice that `j/format` does key processing, but to access the formatters array directly, I made a helper function:

``` clojure
```

**Comment by dm3** [comment]
`java-time.format/predefined-formatters` is supposed to be private. The only public API namespaces are `java-time` and `java-time.repl`.

Could you please explain why you need the access to predefined formatters separately from the `j/format` function? Maybe we'll think of something to add to the public API.

**Comment by yayitswei** [comment]
How would you parse a string with a predefined formatter?

**Comment by jacobemcken** [comment]
> How would you parse a string with a predefined formatter?

Like so:
```
user=> (j/format :iso-offset-time (j/zoned-date-time))
"21:10:00.000+01:00"
```
You can still reference predefined formats (like `:iso-offset-time`) without having them in a map.

See the response by dm3 cfrom Jul 12, 2018.

**Comment by dm3** [comment]
Added API comments to `j/format`
