### ISSUE TITLE
Support for Duration unit expressions/coercions?

### ISSUE THREAD

**Issue by dball** [dm3/clojure.java-time#3]
Is there a way to get the value of a Duration in a unit, e.g. the number of seconds in a duration? Without resorting to interop, that is.

If you do not already have this capability, maybe something like:

`(in duration :seconds)`

since you've already committed to keyword representations of the various units as a part of the api in other calls?

**Comment by dm3** [comment]
Hi,

you can use `java-time/as`, e.g. 

```clj
user=> (as (duration 10 :days) :seconds)
864000
```

I would expect most of the API to have examples in the readme. Would welcome a PR if the readme is lacking! :)

**Comment by dm3** [comment]
Closing this one.
