### ISSUE TITLE
Document how to compute differences between dates, e.g. nr. days between two dates

### ISSUE THREAD

**Issue by holyjak** [dm3/clojure.java-time#44]
Should we just use `.until` or is there something built-in? In any case it would be worth documenting, finding out how many days / months / ... is between two days is common I'd believe.
Now I do

```clojure
(.until (jt/local-date "2019-01-01") (jt/local-date "2019-02-13") (java.time.temporal.ChronoUnit/DAYS))
```

I have tried to do

```clojure
(jt/as (jt/period (jt/local-date "2019-01-01") (jt/local-date "2019-02-13")) :days)
``` but it fails with "Period contains years or months"

**Comment by lucasemmoreira** [comment]
I would like to now this information as well. Thanks for your solution, @holyjak ! It worked here.

**Comment by dm3** [comment]
The readme provides an example of doing this:

```
(j/time-between :days (jt/local-date "2019-01-01") (jt/local-date "2019-02-13"))
43
```
