### ISSUE TITLE
Consider the `Datafiable` protocol to expose a pure-data view of returned objects

### ISSUE THREAD

**Issue by jimpil** [dm3/clojure.java-time#46]
Hi there, 

First of all, many thanks for your work on this - it is hugely appreciated :). Secondly, i think this library fits perfectly into the intended use-cases for the new `Datafiable` protocol (Clojure 1.10). Any top-level object (e.g. LocalDateTime, ZonedDateTime etc) could/should be datafiable, and this would essentially remove the need for Java interop (for accessing individual fields) in the vast majority of cases. Would  you be interested in a PR? It would boil down to a brand new `data` namespace exposing a single public `to-data`. 

Again, thanks for your work... ;)

**Comment by dm3** [comment]
Sure, sounds good. Would be interesting to see what you come up with!

**Comment by jimpil** [comment]
See #47

**Comment by dm3** [comment]
Closed together with PR after some discussions.
