### ISSUE TITLE
Extra leading hyphen in month-day output

### ISSUE THREAD

**Issue by Jacob-Kroeze** [dm3/clojure.java-time#50]
https://github.com/dm3/clojure.java-time/blob/494e18144dc0e24c927a9b9f3ac792ce00457768/src/java_time/single_field.clj#L186

`(str (t/month-day)) ;; => "--02-04"`

**Comment by dm3** [comment]
I'm not sure what's the reason for this, but this is how the `toString` is defined in Java:

```
user=> (MonthDay/now)
#object[java.time.MonthDay 0x73fc8857 "--02-06"]
```

I don't think we should change the behaviour for this specific time entity given all others use the native Java `toString`. What do you think?

**Comment by dm3** [comment]
Closing as not actionable.
