### ISSUE TITLE
unexpected results for before? after? on interval

### ISSUE THREAD

**Issue by thumbnail** [dm3/clojure.java-time#52]
According to the [threethen javadoc](https://www.threeten.org/threeten-extra/apidocs/org.threeten.extra/org/threeten/extra/Interval.html#isAfter(org.threeten.extra.Interval)) an interval is `start inclusive and the end exclusive.`.

The javadoc of the `isBefore` and `isAfter` reflect this:
> Since intervals do not include their end points, this will return true if the instant equals the end of the interval.

Using java-time however, this is not the case:
```clj
i
=> #object[org.threeten.extra.Interval 0x17e871bf "2018-01-01T00:00:00Z/2019-01-01T00:00:00Z"]
i2
=> #object[org.threeten.extra.Interval 0x51897443 "2019-01-01T00:00:00Z/2020-01-01T00:00:00Z"]
(.isBefore i i2)
=> true
(java-time/before? i i2)
=> false
```

The issue is a custom impl for `single-before?` and `single-after?`: https://github.com/dm3/clojure.java-time/blob/494e18144dc0e24c927a9b9f3ac792ce00457768/src/java_time/interval.clj#L112-L118

and can be mitigated by evalling
```clj
(extend-type Interval
  jt.c/Ordered
  (single-before? [i o] (.isBefore i o))
  (single-after? [i o] (.isAfter i o)))
```

**Comment by dm3** [comment]
This is a problem. I'm not sure why I did the `single-before?/after?` on the `Interval` this way. Seems like delegating to the `.isBefore/After` should be the right choice. Will look into it.

**Comment by dm3** [comment]
I've just looked briefly - looks like the `single-before?/after?` were defined before there was an `.isBefore/After` implementation in Interval add in [a134f48ef6f445](https://github.com/ThreeTen/threeten-extra/commit/a134f48ef6f4450fb4804ac16ed6d0834668e41f).

**Comment by frenchy64** [comment]
https://github.com/dm3/clojure.java-time/commit/dfdf7d19f2b70d8eec38530ac87b24aae736ea1f
