### ISSUE TITLE
No such var: t/interval

### ISSUE THREAD

**Issue by crclark** [dm3/clojure.java-time#54]
```
lein --version
Leiningen 2.9.3 on Java 1.8.0_212 OpenJDK 64-Bit Server VM
```

Using clojure 1.10.0 and java-time 0.3.2,

```
user=> (require '[java-time :as t])
nil
user=> (t/interval (t/instant) (t/instant))
Syntax error compiling at (target/8d19c48038470b12302e74f763fae3e2d7e82d87-init.clj:1:1).
No such var: t/interval
```

But I see `interval` [in the docs](http://dm3.github.io/clojure.java-time/java-time.html#var-interval). Am I missing something obvious?

~I also just noticed that tab completion seems to give me a non-deterministic count of the number of things in the namespace when I restart `lein repl`.~ Edit: this part was me confusing myself when downgrading to java-time 0.3.0 to see if it contained `interval`. Neither 0.3.0 nor 0.3.2 seem to contain the function.

**Comment by dm3** [comment]
Hey! You need to add `three-ten-extra` as a dependency as outlined in the [README](https://github.com/dm3/clojure.java-time#three-ten-extra).

**Comment by crclark** [comment]
Thanks! I was only looking at the API docs. Maybe it would be worth mentioning `three-ten-extra` in the docstrings of those functions, too.

**Comment by dm3** [comment]
Added API comment on `j/interval`
