### ISSUE TITLE
Eastwood linter gives "implicit-dependencies" warnings

### ISSUE THREAD

**Issue by pmonks** [dm3/clojure.java-time#62]
In my code I believe I've pulled in java-time correctly, using code such as:
```clojure
(ns my.ns
  (:require [java-time :as tm]))
```
and then called java-time fns including:
* `tm/instant`
* `tm/zoned-date-time`
* `tm/local-date`
* `tm/format`
* `tm/plus`
* `tm/minus`
* `tm/after?`
* etc.

However when I run the [eastwood linter](https://github.com/jonase/eastwood) over my code, it gives an [`implicit-dependences` warning](https://github.com/jonase/eastwood#whats-there) for each java-time fn I'm calling.

Am I requiring java-time incorrectly, is the `java-time` ns not requiring all of the various other java-time-internal namespaces properly, or is this a false negative from eastwood?  My code certainly seems to be functioning correctly, fwiw.

**Comment by dm3** [comment]
You are using `java-time` correctly. This is an [issue #307 with Eastwood](https://github.com/jonase/eastwood/issues/307).

**Comment by pmonks** [comment]
Awesome!  Thank you for the quick reply (and for the library - it's great!).

**Comment by vemv** [comment]
The Eastwood issue has been fixed in its 0.3.14 release
