### ISSUE TITLE
Document how to go from an instant to a ZonedDateTime

### ISSUE THREAD

**Issue by jacobemcken** [dm3/clojure.java-time#64]
I would assume there would be a "prettier" way to convert an instant to a `ZonedDateTime`, because it looks clunky using Java interop (`ofInstant`) like this:
```clojure
(java.time.ZonedDateTime/ofInstant (java-time/instant "2021-05-16T22:00:00Z") (java-time/zone-id "Europe/Copenhagen"))
```

Is this the "best" way?

**Comment by dm3** [comment]
`(j/zoned-date-time (j/instant) "UTC")` works. Am I missing something in the question?

**Comment by jacobemcken** [comment]
I think you hit the spot, thanks.

Looking at the [documentation for converstions](https://github.com/dm3/clojure.java-time#conversions) it might be an idea to include the above example.

Since `j/zoned-date-time` can be called without a zone in both these cases:
```clojure
(j/zoned-date-time)
(j/zoned-date-time (offset-date-time 2015 9 28 1))
```
I probably assumed I could do it with an instant as well:
```clojure
(java-time/zoned-date-time (java-time/instant))
```

Instead I got this not so readable exception:
```
1. Unhandled clojure.lang.ExceptionInfo
   Could not convert [#object[java.time.Instant 0x281410c4
   "2021-03-23T13:51:48.768Z"]] to class java.time.ZonedDateTime!
...
```
