### ISSUE TITLE
Vars in the `java-time` namespace do not get resolved in Cursive

### ISSUE THREAD

**Issue by dm3** [dm3/clojure.java-time#8]
Due to the var import, the vars in the `java-time` namespace do not get autocompleted.

Issue registered with Cursive project at https://github.com/cursive-ide/cursive/issues/1670.

**Comment by dm3** [comment]
Closed as per the upstream fix.

**Comment by spacegangster** [comment]
Experiencing this again. 
<img width="1680" alt="Screenshot 2020-06-25 at 15 06 47" src="https://user-images.githubusercontent.com/745164/85716893-974efb80-b6f5-11ea-9a6e-29ea72603cde.png">
