### ISSUE TITLE
Consider Removing clj-tuple

### ISSUE THREAD

**Issue by alexanderkiel** [dm3/clojure.java-time#80]
The [clj-tuple](https://github.com/ztellman/clj-tuple) library is old, archived and the performance improvements are [questionable](https://clojure.atlassian.net/browse/CLJ-1517). So I would recommend the just remove the dependency and use the Clojure build-in `vector` function.

**Comment by dm3** [comment]
That's probably a good idea. However, I'm not going to get this done any time soon. If ever. PR welcome!

**Comment by dm3** [comment]
Closed by #81
