### ISSUE TITLE
Cut new release for Clojure 1.11 compat?

### ISSUE THREAD

**Issue by DerGuteMoritz** [dm3/clojure.java-time#84]
Given that Clojure 1.11 is about to be released any day now, how about cutting a new release which includes https://github.com/dm3/clojure.java-time/pull/83 to get rid of the warning? Thanks for the library! :pray:

**Comment by Heliosmaster** [comment]
> Given that Clojure 1.11 is about to be released any day now, how about cutting a new release which includes #83 to get rid of the warning? Thanks for the library! 🙏

In the meantime, if you use deps.edn you can just use the revision https://github.com/dm3/clojure.java-time/commit/f9e11c3f852c14adf579d5101e7e98ec198eb343 in your code

**Comment by DerGuteMoritz** [comment]
> In the meantime, if you use deps.edn you can just use the revision [f9e11c3](https://github.com/dm3/clojure.java-time/commit/f9e11c3f852c14adf579d5101e7e98ec198eb343) in your code

Unfortunately not because that would also require `clojure.java-time` to have a  `deps.edn` which it doesn't, yet :grimacing:

**Comment by Heliosmaster** [comment]
whoops, missed that. Can still fork and add it tho 😅

**Comment by DerGuteMoritz** [comment]
Heh yeah went ahead and did just that. See https://github.com/dm3/clojure.java-time/pull/85.

**Comment by dm3** [comment]
Sorry guys, I'm really behind on maintaining this library as I haven't worked with Clojure for years now. Does anyone want to become a maintainer or take over?

**Comment by frenchy64** [comment]
I use this library at work, I can be a maintainer. I have a few PR's open here with fixes.

FWIW I'm also a maintainer of [schema](https://github.com/plumatic/schema) and [plumbing](https://github.com/plumatic/plumbing) for similar reasons.

**Comment by aneilbaboo** [comment]
@dm3 - bumping this thread add @frenchy64 as a maintainer. It would be great to get v0.3.4 published. The abs symbol collision in Clojure 1.11 is causing problems in my IDE:
<img width="357" alt="image" src="https://user-images.githubusercontent.com/2592723/170840708-e010df8e-b687-4cc1-a57c-1ac72a822af3.png">

**Comment by edporras** [comment]
@frenchy64 I can also help maintain, even though I'm also no time expert 😅

I would also like to get a new release published.

**Comment by aneilbaboo** [comment]
Hi @dm3 - just pinging you in the hope you'll see the above messages from @edporras and @frenchy64

**Comment by dm3** [comment]
yep, thanks! I'll take a look now to add maintainers to the project

**Comment by frenchy64** [comment]
@dm3 thanks, please also add https://clojars.org/users/frenchy64 to the https://clojars.org/clojure.java-time group so I can deploy.

**Comment by frenchy64** [comment]
It doesn't look like @dm3 is monitoring this repo, I might deploy it somewhere else.

**Comment by huima** [comment]
I wonder if there is another way to reach him through some other channel instead of starting to publish to some other place.

Would be nice if someone in the Clojure community knows him otherwise:

https://twitter.com/huima/status/1559511570140610562

**Comment by huima** [comment]
Another option could be to open the ticket with Clojars ( https://github.com/clojars/clojars-web/wiki/Contact ) and see if the issue could be resolved through their help. Not sure if there exists yet a process for deciding if the initial maintainer has properly abandoned the project in a way that new maintainers could be given rights also to clojars.

I'll ping them via email - and ask what would be a proper way to proceed if they could investigate giving permissions to clojars that reflect project's current maintainer status too.

**Comment by aneilbaboo** [comment]
@tobias @danielcompton - the original owner of this repo (@dm3) transferred it to @frenchy64 and others, but did not add them to the Clojars repo, and also isn't monitoring Github anymore, it seems. 

What is the right way to get this resolved?

**Comment by tobias** [comment]
Hi all! We should be able to help out here. Based on my reading of this issue, it does seem like @dm3's intent is to let @frenchy64 be a maintainer, which would include Clojars deploy rights. I have emailed the address we have on file for @dm3 in Clojars to confirm that, and I can add @frenchy64 to the group when I hear back. 

If I don't hear back in a reasonable time (a few days), we can discuss other options.

**Comment by arohner** [comment]
@tobias Any updates?

**Comment by tobias** [comment]
@arohner: Sorry for the delay here. I haven't heard anything back from @dm3. 

Given the discussion here, I think it's fine to give @frenchy64 access to the group on Clojars. I'm away from a computer the rest of the month, but @danielcompton should be able to help.

**Comment by danielcompton** [comment]
Yep I'll do this in the next day or so.

**Comment by danielcompton** [comment]
@frenchy64 you are now an admin for the clojure.java-time group on Clojars, along with @dm3.

**Comment by frenchy64** [comment]
@danielcompton there's a typo: I'm `frenchy64`, you seem to have given `french64` access.

**Comment by danielcompton** [comment]
@frenchy64 sorry about that, I've removed the (nonexistent) user french64 and added you.

There were no new versions published during this period.

**Comment by frenchy64** [comment]
Thanks! Released 1.0.0.
