### ISSUE TITLE
Things like `java-time[.api]/truncate-to` do not work correctly when underlying protocol is extended 

### ISSUE THREAD

**Issue by camsaul** [dm3/clojure.java-time#95]
In Metabase we extended the `Truncatable` protocol with some tweaks that we needed to handle certain situations:

https://github.com/metabase/metabase/blob/d0be9fc4c291438204e792f3981bf7fe5a42878a/src/metabase/util/date_2.clj#L289-L298

Previously, we were using a fork of 0.3.3, where the `java-time` namespace used Potemkin `import-vars`, which meant that `java-time/truncate-to` would be updated when the underlying `java-time.core/truncate-to` var changed (when using `extend`/`extend-protocol`/etc.

The newer version of this namespace just uses `def` to capture the value of `java-time.core/truncate-to` when the namespace is loaded; any subsequent changes to the underlying var no longer cause `java-time/truncate-to` or `java-time.api/truncate-to` to be updated.

I spent a little while trying to debug 

```
java.lang.IllegalArgumentException: No implementation of method: :truncate-to of protocol: #'java-time.core/Truncatable found for class: java.time.LocalDate
```

errors in Metabase after upgrading to the latest version of this library until I figured out what was going on.

Switching back to Potemkin would prevent others from running in to issues like these. Alternatively, instead of something like

```clj
(ns java-time.api ...)

(def truncate-to java-time.core/truncate-to)
```

maybe you could do

```clj
(def truncate-to #'java-time.core/truncate-to)
```

or even

```clj
(defn truncate-to [t unit] (java-time.core/truncate-to t unit))
```

so the var gets resolved each time you use it.

**Comment by frenchy64** [comment]
Thanks for the detailed report. I'll think it over.

Notes:
- the root cause is https://clojure.atlassian.net/browse/CLJ-1796
- I wonder how this interacts with direct linking.
  - do extends need to happen before usages in general?

**Comment by frenchy64** [comment]
@camsaul tangentially related, do you compile your app with direct linking?

**Comment by frenchy64** [comment]
Fixed in 1.2.0.

**Comment by camsaul** [comment]
@frenchy64, no we don't use direct linking

**Comment by frenchy64** [comment]
@camsaul thanks. I since learnt that protocols methods are never directly linked.
